name: Publish to Package Registry

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag or release name to publish"
        required: true
        type: string

permissions:
  contents: read
  packages: write  # needed for GitHub Packages

jobs:
  publish:
    name: Publish Wheels & SDist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dist
          gh release download ${{ inputs.tag }} --pattern "*.whl" --pattern "*.tar.gz" --dir dist

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          activate-environment: true
          python-version: "3.12"

      - name: Verify downloaded files
        run: ls -lh dist/

      - name: Publish to GitHub Packages
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv publish \
            --publish-url https://pypi.pkg.github.com/${{ github.repository_owner }} \
            --token $UV_PUBLISH_TOKEN \
            --verbose
